### PR TITLE
Create Vendor list + associated work

### LINKED ISSUE #4: Old Doc Port: The Process
Port the section labeled "The Process" from the old document to here.

### PR DESCRIPTION
**Pull request by izzygaafar**
Functioning hyperlinks for NA vendors, and a slightly modified kitting section;  so it doesn't look as unprofessional.

### CODE REVIEW

**Comment by acitrin** [comment]
I'm asking @nopunin10did to take a look at this.

My first inclination is that the file re: kitting might not be the best way to phrase it... given that portraying a "typical" kitting might not go well.

The vendor list looks good... but I'm not sure how to break it so it's not a huge page.

**Comment by izzygaafar** [comment]
Was going to mention the support that typical kitting includes, not show a specific base kit, if that was your concern. I could turn the vendor list into a graph if needed, I just gotta add links.

**Comment by acitrin** [comment]
> Was going to mention the support that typical kitting includes, not show a specific base kit, if that was your concern. 

Yeah, I think that might be something worth rewording 😅 

> I could turn the vendor list into a graph if needed, I just gotta add links.

I meant further breaking down the `The Process` page to include some subpages so it's not an endless wall of text. The formatting on the vendor list is fine as-is right now 👍

**Comment by izzygaafar** [comment]
Alright gotcha,

**Review by nopunin10did — APPROVED** [review]

**Pull request merged**
